#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"

IFS=:
if stest -dqr -n "$cache" $PATH; then
	stest -flx $PATH | grep -v -f dmenu_exclude | sort -u | tee "$cache"
else
	cat "$cache"
fi
